import type { Metadata } from 'next';
import TurkishTrustPage from '@/components/TurkishTrustPage';

export const metadata: Metadata = { title: { absolute: 'Gizlilik Politikası | DearPassengers.net Türkçe' }, description: 'DearPassengers.net Türkçe bölümünde gizlilik, çerez, reklam, analiz, dış bağlantı ve iletişim verilerinin kullanımı.', alternates: { canonical: '/tr/gizlilik/', languages: { en: '/privacy-policy/', ar: '/ar/privacy-policy/', de: '/de/datenschutz/', tr: '/tr/gizlilik/', 'pt-BR': '/pt-br/privacidade/', 'x-default': '/privacy-policy/' } } };
export default function TurkishPrivacyPage() { return <TurkishTrustPage title="Gizlilik politikası" englishPath="/privacy-policy/" lede="Bu özet, DearPassengers.net Türkçe bölümünde hangi teknik verilerin oluşabileceğini ve gizlilik seçeneklerine nasıl erişileceğini açıklar." sections={[
  { heading: 'Toplanan bilgiler', paragraphs: ['Sunucu ve analiz araçları IP adresi, cihaz, tarayıcı, yönlendiren sayfa ve ziyaret edilen URL gibi teknik verileri işleyebilir. İletişim kurarsanız gönderdiğiniz e-posta ve mesajı talebi yanıtlamak için kullanırız.', 'Site oyun hesabı, Steam şifresi, ödeme kartı veya Dear Passengers dosyası toplamaz.'] },
  { heading: 'Çerezler, reklam ve onay', paragraphs: ['Site ölçüm, güvenlik ve reklam hizmetleri kullanabilir. Bölgenizde gerekli olduğunda onay arayüzü gösterilir; mevcutsa altbilgideki gizlilik ve çerez ayarlarından tercihlerinizi yeniden açabilirsiniz.', 'Üçüncü taraf hizmetler kendi politikalarına göre veri işleyebilir. Reklam, editoryal gerçek sınıfını değiştirmez.'] },
  { heading: 'Dış bağlantılar', paragraphs: ['Steam, YouTube ve diğer birincil kaynak bağlantıları kendi sitelerine gider. Bu sitelerin içerik ve veri uygulamalarını kontrol etmiyoruz.', 'Bilinmeyen indirme, APK veya crack bağlantısı vermememizin nedeni hem doğruluk hem güvenliktir.'] },
  { heading: 'Haklar ve iletişim', paragraphs: ['Geçerli mevzuata göre erişim, düzeltme veya silme talebinizi hello@dearpassengers.net adresine gönderebilirsiniz. Talebin doğrulanması için makul bilgi istenebilir.', 'Politika önemli biçimde değişirse tarih güncellenir. Yalnız biçimsel düzeltmeler sahte yeni tarih üretmez.'] },
]} />; }
