import type { Metadata } from 'next';
import TurkishTrustPage from '@/components/TurkishTrustPage';

export const metadata: Metadata = { title: { absolute: 'DearPassengers.net Hakkında: Bağımsız Türkçe Rehber' }, description: 'Dear Passengers Türkçe rehberinin amacı, bağımsızlığı, kaynak yöntemi, yerelleştirme yaklaşımı ve düzeltme süreci.', alternates: { canonical: '/tr/hakkimizda/', languages: { en: '/about/', ar: '/ar/about/', de: '/de/ueber-uns/', tr: '/tr/hakkimizda/', 'pt-BR': '/pt-br/sobre/', 'x-default': '/about/' } } };
export default function TurkishAboutPage() { return <TurkishTrustPage title="DearPassengers.net hakkında" englishPath="/about/" lede="DearPassengers.net, Dear Passengers oyunu için bağımsız ve resmî olmayan bir bilgi rehberidir. Türkçe bölüm makine çevirisi olarak değil, Türkiye’deki gerçek arama soruları ve yerleşik oyun terimleri araştırılarak oluşturuldu." sections={[
  { heading: 'Neleri kapsıyoruz?', paragraphs: ['Oynanış, roller, oyuncu sayısı, çıkış tarihi, demo, güvenli indirme, sistem gereksinimleri, fragman, haberler ve FLEXUS geliştirici profili için ayrı ama bağlantılı rehberler sunuyoruz.', 'Oyun dosyası, APK veya anahtar barındırmıyoruz. Birincil kaynakta olmayan fiyat, tarih, platform, özellik veya oyuncu sınırı yayımlamıyoruz.'] },
  { heading: 'Türkçe içeriği nasıl hazırlıyoruz?', paragraphs: ['GSC ve yerel arama sonuçlarında görülen “indir”, “sistem gereksinimleri”, “ne zaman çıkacak” ve “kaç kişilik” gibi doğal ifadeleri kullanıyoruz. Dear Passengers marka adı çevrilmeden korunuyor.', 'Steam, FLEXUS kanalları ve doğrudan röportajlar ürün gerçeği için önceliklidir. Forumlar ve medya, soruyu keşfetmeye yardımcı olabilir; tek başına özelliği doğrulamaz.'] },
  { heading: 'Bağımsızlık ve görsel hakları', paragraphs: ['DearPassengers.net; FLEXUS, Valve veya Steam’e bağlı değildir. Reklam ilişkisi bir bilginin kanıt statüsünü değiştirmez.', 'Resmî görseller editoryal inceleme bağlamında kullanılır ve hakları sahiplerine aittir. Editoryal bir görseli resmî ekran görüntüsü olarak göstermeyiz.'] },
  { heading: 'Düzeltmeler', paragraphs: ['Bir hata, kaynak bağlantısıyla iletişim sayfasından gönderilebilir. Değişiklikten önce kaynak kontrol edilir ve ortak gerçekse diğer dil sürümleri de incelenir.', 'Zamana duyarlı içerik kontrol tarihi taşır. Resmî cevap yoksa bilgi, yeni kanıt gelene kadar “bilinmiyor” olarak kalır.'] },
]} />; }
