import type { Metadata } from 'next';
import PortugueseTrustPage from '@/components/PortugueseTrustPage';

export const metadata: Metadata = { title: { absolute: 'Política de Privacidade | DearPassengers.net Brasil' }, description: 'Dados técnicos, cookies, publicidade, análise, links externos e contato no guia brasileiro do DearPassengers.net.', alternates: { canonical: '/pt-br/privacidade/', languages: { en: '/privacy-policy/', ar: '/ar/privacy-policy/', de: '/de/datenschutz/', tr: '/tr/gizlilik/', 'pt-BR': '/pt-br/privacidade/', 'x-default': '/privacy-policy/' } } };
export default function PortuguesePrivacyPage() { return <PortugueseTrustPage title="Política de privacidade" englishPath="/privacy-policy/" lede="Este resumo explica quais dados técnicos podem ser processados no DearPassengers.net e como reabrir as opções de privacidade quando elas estiverem disponíveis." sections={[
  { heading: 'Informações processadas', paragraphs: ['Servidor e ferramentas de análise podem processar endereço IP, dispositivo, navegador, página de referência e URL visitada. Se você entrar em contato, o e-mail e a mensagem enviados serão usados para avaliar e responder à solicitação.', 'O site não coleta senha da Steam, cartão de pagamento, conta do jogo nem arquivo de Dear Passengers.'] },
  { heading: 'Cookies, anúncios e consentimento', paragraphs: ['O site pode usar serviços de medição, segurança e publicidade. Onde for necessário, uma interface de consentimento será exibida; o botão de configurações no rodapé permite reabrir as escolhas quando o serviço estiver ativo.', 'Fornecedores externos podem processar dados de acordo com suas próprias políticas. A presença de publicidade não muda o padrão editorial ou a classificação de evidências.'] },
  { heading: 'Links externos', paragraphs: ['Links para Steam, YouTube e outras fontes primárias levam a serviços independentes, cujas práticas de conteúdo e dados não são controladas por este site.', 'Não oferecer arquivos desconhecidos, APKs ou cracks reduz riscos de segurança e evita induzir o visitante a um download inexistente.'] },
  { heading: 'Direitos e contato', paragraphs: ['Solicitações de acesso, correção ou exclusão aplicáveis podem ser enviadas a hello@dearpassengers.net. Podemos pedir informações razoáveis para verificar o pedido e localizar os dados relacionados.', 'A data da política muda quando ocorre alteração relevante. Ajustes de redação ou formatação não recebem uma falsa data de atualização.'] },
]} />; }
