import type { Metadata } from 'next';
import PortugueseTrustPage from '@/components/PortugueseTrustPage';

export const metadata: Metadata = { title: { absolute: 'Contato e Correções | DearPassengers.net Brasil' }, description: 'Como enviar uma fonte, correção, aviso de direitos autorais ou pedido de privacidade ao guia brasileiro de Dear Passengers.', alternates: { canonical: '/pt-br/contato/', languages: { en: '/contact/', ar: '/ar/contact/', de: '/de/kontakt/', tr: '/tr/iletisim/', 'pt-BR': '/pt-br/contato/', es: '/es/contacto/', 'x-default': '/contact/' } } };
export default function PortugueseContactPage() { return <PortugueseTrustPage title="Contato e correções" englishPath="/contact/" lede="Você pode compartilhar uma correção verificável, uma nova fonte primária ou uma notificação de direitos relacionada ao conteúdo sobre Dear Passengers." sections={[
  { heading: 'Como enviar uma correção', paragraphs: ['Informe a URL da página, a frase que considera incorreta e, se possível, o link da Steam, FLEXUS ou entrevista direta que sustenta a mudança. Não publicamos datas, preços ou números de jogadores enviados sem origem.', 'Se o fato do produto for comum a todas as regiões, as versões em inglês, alemão, árabe, chinês, turco e português brasileiro serão avaliadas em conjunto.'] },
  { heading: 'Endereço de contato', paragraphs: ['E-mail: hello@dearpassengers.net. Use no assunto “correção pt-BR”, “fonte”, “direito de imagem” ou “privacidade” para facilitar a triagem.', 'DearPassengers.net não presta suporte ao jogo nem processa compras e reembolsos. Questões de conta ou loja devem ser encaminhadas ao suporte oficial da Steam.'] },
  { heading: 'Direitos autorais e imagens', paragraphs: ['Se você representa o titular, indique a URL da imagem e o alcance do pedido. Material oficial é apresentado em contexto editorial, sem alegação de propriedade.', 'Uma ilustração editorial ou gerada não recebe o rótulo de captura oficial. Caso a identificação esteja errada, corrigiremos a legenda e a origem após a verificação.'] },
  { heading: 'Resposta e registro', paragraphs: ['Não é possível garantir resposta individual a todas as mensagens, mas correções documentadas recebem prioridade. Dados pessoais são usados para avaliar a solicitação e, quando necessário, responder.', 'Sugestões de recurso não são fatos do produto. Elas podem ajudar a entender interesse editorial, porém só entram em conteúdo factual quando surgem evidências.'] },
]} />; }
