import type { Metadata } from 'next';
import PortugueseTrustPage from '@/components/PortugueseTrustPage';

export const metadata: Metadata = { title: { absolute: 'Política Editorial e Verificação | Dear Passengers Brasil' }, description: 'Como o guia brasileiro classifica informações confirmadas, observações, planos e lacunas sobre Dear Passengers.', alternates: { canonical: '/pt-br/politica-editorial/', languages: { en: '/editorial-policy/', ar: '/ar/editorial-policy/', de: '/de/redaktionsrichtlinien/', tr: '/tr/editorial-policy/', 'pt-BR': '/pt-br/politica-editorial/', 'x-default': '/editorial-policy/' } } };
export default function PortugueseEditorialPolicyPage() { return <PortugueseTrustPage title="Política editorial em português" englishPath="/editorial-policy/" lede="Nosso objetivo não é parecer o primeiro a saber, mas permitir que o leitor entenda a força de cada afirmação sobre Dear Passengers." sections={[
  { heading: 'Classificação das evidências', paragraphs: ['“Confirmado” vem de um campo da Steam ou de uma declaração clara da FLEXUS. “Observação” limita-se ao que uma imagem ou vídeo oficial mostra. “Plano” é uma intenção da desenvolvedora e ainda pode mudar. “Não informado” assume que falta evidência suficiente.', 'Um rumor, uma ficha automática ou uma data de preenchimento não ganham força porque foram copiadas por muitos sites. Procuramos a origem antes de repetir o dado.'] },
  { heading: 'Prioridade das fontes', paragraphs: ['Steam é a principal referência para plataforma, modos, idiomas e requisitos. Comunicados oficiais e entrevistas diretas identificadas complementam planos e contexto da desenvolvedora. Uma matéria só serve de prova para o que ela própria consegue documentar.', 'Rankings, listas de desejos e outros números variáveis recebem data e atribuição. Eles não são convertidos em vendas, jogadores ativos ou sucesso financeiro sem uma fonte específica.'] },
  { heading: 'Padrão de localização', paragraphs: ['Títulos e textos brasileiros não copiam a ordem das frases em inglês. Pesquisamos consultas locais, terminologia da Steam, formato de data e preocupações de segurança do público brasileiro.', 'Ter um guia em pt-BR não significa que o jogo ofereça menus, áudio ou legendas nesse idioma. A situação oficial do produto é apresentada separadamente.'] },
  { heading: 'Atualizações e correções', paragraphs: ['Quando surge uma fonte importante, revisamos o tema afetado e seus equivalentes de idioma. Ajustes puramente visuais ou ortográficos não recebem uma data artificial de atualização factual.', 'Pedidos de correção são avaliados com a fonte enviada. Caso a evidência mude, o novo estado e a data da conferência ficam visíveis no conteúdo.'] },
]} />; }
