import type { Metadata } from 'next';
import PortugueseTrustPage from '@/components/PortugueseTrustPage';

export const metadata: Metadata = { title: { absolute: 'Sobre o DearPassengers.net: Guia Brasileiro Independente' }, description: 'Objetivo, independência, pesquisa local, fontes e processo de correção do guia brasileiro de Dear Passengers.', alternates: { canonical: '/pt-br/sobre/', languages: { en: '/about/', ar: '/ar/about/', de: '/de/ueber-uns/', tr: '/tr/hakkimizda/', 'pt-BR': '/pt-br/sobre/', es: '/es/sobre/', 'my-MM': '/my/about/', 'x-default': '/about/' } } };
export default function PortugueseAboutPage() { return <PortugueseTrustPage title="Sobre o DearPassengers.net" englishPath="/about/" lede="DearPassengers.net é um guia independente e não oficial sobre o jogo Dear Passengers. A seção brasileira não é tradução automática: ela foi planejada a partir das perguntas que usuários do Brasil realmente pesquisam e do vocabulário usado no mercado local." sections={[
  { heading: 'O que cobrimos?', paragraphs: ['Mantemos guias relacionados, mas distintos, sobre jogabilidade, funções, número de jogadores, lançamento, demo, download seguro, requisitos, trailers, notícias e a desenvolvedora FLEXUS.', 'Não hospedamos arquivos do jogo, APKs nem chaves. Preço, data, plataforma, recurso e limite de jogadores só recebem status confirmado quando uma fonte primária publica a informação.'] },
  { heading: 'Como produzimos conteúdo brasileiro?', paragraphs: ['Consultas como “data de lançamento”, “quando lança”, “requisitos”, “baixar”, “preço” e “quantos jogadores” orientam a arquitetura. O nome Dear Passengers permanece em inglês porque é uma marca; o restante é redigido de forma natural em português brasileiro.', 'Steam, canais da FLEXUS e entrevistas diretas têm prioridade para fatos do produto. Fóruns e matérias locais ajudam a encontrar dúvidas e expressões, mas não comprovam uma mecânica por conta própria.'] },
  { heading: 'Independência e direitos de imagem', paragraphs: ['DearPassengers.net não pertence a FLEXUS, Valve ou Steam. Publicidade ou relações comerciais não alteram a classificação de evidências.', 'Imagens oficiais são usadas em contexto editorial e continuam pertencendo a seus titulares. Imagens editoriais ou geradas nunca são apresentadas como captura oficial do jogo.'] },
  { heading: 'Correções', paragraphs: ['Uma correção pode ser enviada pela página de contato com a URL e a fonte correspondente. Antes de alterar o texto, verificamos a origem; quando o fato é comum, avaliamos as outras versões de idioma.', 'Conteúdo sensível ao tempo mostra data de conferência. Na ausência de resposta oficial, mantemos “não informado” em vez de fabricar uma resposta.'] },
]} />; }
