import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import path from 'node:path';import {chromium,launchOptions,outputDir} from './flight-qa-runtime.mjs';
const browser=await chromium.launch(launchOptions);const context=await browser.newContext({viewport:{width:800,height:500}}),host=await context.newPage(),guest=await context.newPage(),report=[],errors=[];
for(const p of [host,guest])p.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){try{await fn();report.push({name,passed:true});console.log('PASS',name);}catch(e){report.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);console.log('DEBUG',JSON.stringify(await host.evaluate(()=>({phase:game.state.phase,elapsed:game.state.elapsed,belts:game.state.belts,served:game.state.served,crew:Array.from(game.crewPlayers.values()).map(p=>({id:p.id,pose:p.pose,item:p.item,action:p.action})),errors:window.roomErrors})).catch(()=>null)));console.log('GUEST',JSON.stringify(await guest.evaluate(()=>({phase:game.state.phase,pos:game.position.toArray(),state:game.state})).catch(()=>null)));}}
async function aim(page,id){await page.evaluate(id=>{const g=window.game,target=g.targets.find(t=>t.id===id).pos();g.position.set(Math.abs(target.x)>1?Math.sign(target.x)*.85:0,1.65,target.z+1.2);const d=target.clone().sub(g.position);g.yaw=Math.atan2(-d.x,-d.z);g.pitch=Math.atan2(d.y,Math.hypot(d.x,d.z));g.velocity.set(0,0,0);},id);await page.waitForFunction(id=>window.flight.target===id,id,{timeout:10000});await page.waitForTimeout(350);}
async function act(page){await page.evaluate(()=>window.game.interact());}
try{
for(const p of [host,guest]){await p.goto('http://127.0.0.1:8898');await p.waitForFunction(()=>window.game);await p.evaluate(()=>window.game.quality());}
await check('Two real WebSocket clients join the same flight room',async()=>{const code=await host.evaluate(async()=>{window.room=await Flight.createFlightRoom('http://127.0.0.1:8789','Captain');window.game.connectCrew(window.room);window.roomErrors=[];window.room.subscribe(e=>{if(e.type==='error')window.roomErrors.push(e)});return window.room.code;});await guest.evaluate(async code=>{window.room=await Flight.joinFlightRoom('http://127.0.0.1:8789',code,'Crew Two');window.game.connectCrew(window.room);},code);await host.waitForFunction(()=>window.room.players.length===2);assert.equal(await guest.evaluate(()=>window.room.players.length),2);});
await check('Host starting a contract starts the same mission for guest',async()=>{await host.evaluate(()=>window.game.start({mission:3,route:1,difficulty:'training',upgradeHull:0,upgradeService:0,upgradeHandling:0,riskyCargo:true}));await guest.waitForFunction(()=>window.flight.phase==='playing');assert.equal(await guest.evaluate(()=>window.game.simulation.config.mission),3);});
await check('Guest seatbelt action updates authoritative host and both HUD states',async()=>{await aim(guest,'pax-0');await act(guest);await host.waitForFunction(()=>window.flight.belts===1,null,{timeout:12000});await guest.waitForFunction(()=>window.flight.belts===1);});
await check('Crew members have separate inventories while sharing service progress',async()=>{await aim(host,'galley');await act(host);await aim(guest,'galley');await act(guest);await guest.waitForFunction(()=>window.flight.item==='coffee');await aim(guest,'pax-0');await act(guest);await host.waitForFunction(()=>window.flight.served===1,null,{timeout:12000});assert.equal(await host.evaluate(()=>window.flight.cups),3);await guest.waitForFunction(()=>window.flight.served===1&&window.flight.cups===2,null,{timeout:8000});});
await check('Guest can pilot while host remains free to work in cabin',async()=>{await aim(guest,'cockpit');await act(guest);await guest.waitForFunction(()=>window.flight.piloting);assert.equal(await host.evaluate(()=>window.flight.piloting),false);await host.waitForFunction(()=>window.flight.stage==='takeoff');await host.screenshot({path:path.join(outputDir,'coop-host.png')});await guest.screenshot({path:path.join(outputDir,'coop-pilot.png')});});
await check('Remote pilot controls change shared aircraft bank',async()=>{await guest.evaluate(()=>window.game.toggleAutopilot());await host.waitForFunction(()=>!window.flight.autopilot);await guest.evaluate(()=>window.game.move(.8,0));await host.waitForFunction(()=>window.flight.bank>8,null,{timeout:12000});await guest.evaluate(()=>window.game.move(0,0));assert(Math.abs((await host.evaluate(()=>window.flight.bank))-(await guest.evaluate(()=>window.flight.bank)))<8);await guest.evaluate(()=>window.game.toggleAutopilot());});
await check('Pausing a remote pilot clears steering and engages autopilot',async()=>{await guest.evaluate(()=>{window.game.toggleAutopilot();window.game.move(.7,0);});await host.waitForFunction(()=>!window.flight.autopilot);await guest.evaluate(()=>window.game.pause());await host.waitForFunction(()=>window.flight.autopilot);assert.equal(await host.evaluate(()=>window.game.guestControls.roll),0);await guest.evaluate(()=>window.game.resume());});
await check('Cockpit ownership blocks a second simultaneous pilot',async()=>{await aim(host,'cockpit');await act(host);assert.equal(await host.evaluate(()=>window.flight.piloting),false);assert.equal(await guest.evaluate(()=>window.flight.piloting),true);await act(guest);await guest.waitForFunction(()=>!window.flight.piloting);await act(host);await host.waitForFunction(()=>window.flight.piloting);});
await check('Shared physical objects carry type and reconcile deletions at the 12-object cap',async()=>{await host.evaluate(()=>{const g=window.game;for(let i=0;i<15;i++){g.setItem('coffee');g.state.piloting=false;g.drop();}});await guest.waitForFunction(()=>window.game.bodies.filter(b=>b.disposable).length===12,null,{timeout:8000});assert.equal(await host.evaluate(()=>window.game.bodies.filter(b=>b.disposable).length),12);const hostIds=await host.evaluate(()=>window.game.bodies.filter(b=>b.disposable).map(b=>b.id).sort());const guestIds=await guest.evaluate(()=>window.game.bodies.filter(b=>b.disposable).map(b=>b.id).sort());assert.deepEqual(guestIds,hostIds);});
await check('Guest departure removes avatar and keeps host flight alive',async()=>{await guest.evaluate(()=>window.room.close());await host.waitForFunction(()=>window.room.players.length===1);assert.equal(await host.evaluate(()=>window.game.crewPlayers.size),0);assert.equal(await host.evaluate(()=>window.flight.phase),'playing');});
await check('No multiplayer runtime errors',async()=>assert.deepEqual(errors,[]));
}finally{writeFileSync(path.join(outputDir,'coop-report.json'),JSON.stringify(report,null,2));await host.evaluate(()=>window.room?.close()).catch(()=>{});await browser.close();}if(report.some(r=>!r.passed))process.exitCode=1;
