import type { Metadata } from 'next';
import TurkishTrustPage from '@/components/TurkishTrustPage';

export const metadata: Metadata = { title: { absolute: 'Türkçe Editoryal Politika ve Kaynak Doğrulama' }, description: 'DearPassengers.net Türkçe bölümünün onaylandı, gözlem, plan ve bilinmiyor sınıfları; düzeltme ve güncelleme politikası.', alternates: { canonical: '/tr/editorial-policy/', languages: { en: '/editorial-policy/', ar: '/ar/editorial-policy/', de: '/de/redaktionsrichtlinien/', tr: '/tr/editorial-policy/', 'pt-BR': '/pt-br/politica-editorial/', 'x-default': '/editorial-policy/' } } };
export default function TurkishEditorialPolicyPage() { return <TurkishTrustPage title="Türkçe editoryal politika" englishPath="/editorial-policy/" lede="Amacımız hızlı görünmek değil, Dear Passengers hakkındaki her iddianın ne kadar güçlü olduğunu okuyucunun görebilmesini sağlamaktır." sections={[
  { heading: 'Kanıt sınıfları', paragraphs: ['“Onaylandı”, Steam veya açık FLEXUS açıklamasındaki bilgidir. “Gözlem”, resmî görsel veya videoda görüleni anlatır. “Plan”, geliştiricinin henüz yayımlanmamış hedefidir. “Bilinmiyor”, yeterli kaynak bulunmadığını açıkça söyler.', 'Bir söylenti veya fan tablosu çok sayıda sayfada tekrarlansa da kök kaynağı yoksa güçlenmez.'] },
  { heading: 'Kaynak önceliği', paragraphs: ['Ürün alanları için Steam; stüdyo açıklaması için FLEXUS’un resmî kanalı veya adı belirtilmiş doğrudan röportaj tercih edilir. Medya haberi yalnız kendi doğrulanabilir bilgisini ekliyorsa yardımcı kaynaktır.', 'Dinamik sıralamalar ve istek listesi rakamları tarih ve atıfla yazılır; satış veya oyuncu sayısına dönüştürülmez.'] },
  { heading: 'Yerelleştirme standardı', paragraphs: ['Türkçe başlık ve metinler İngilizce cümle sırasını kopyalamaz. Yerel arama, Steam terminolojisi, sayı/tarih biçimi ve okuyucunun güvenlik beklentileri araştırılır.', 'Yerelleştirme yeni ürün gerçeği yaratmaz. Türkçe rehberin varlığı, resmî oyun arayüzünün kapsamını değiştirmez.'] },
  { heading: 'Güncelleme ve düzeltme', paragraphs: ['Önemli yeni kaynak geldiğinde etkilenen konu ve dil sayfaları birlikte kontrol edilir. Yazım veya tasarım değişikliği yapay yeni tarih oluşturmaz.', 'Düzeltme talepleri kaynakla incelenir. Eski ifade değiştiğinde yeni statü ve kontrol tarihi görünür biçimde güncellenir.'] },
]} />; }
